spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=GMT%2B8
    username: root
    password: 921210
  redis:
    host: 127.0.0.1
    port: 6379

person:
  name: zs
  age: 10
  addr: xinlang
